version: '3'
services:
  client:
    build:
      context: ./client
      # dockerfile: Dockerfile.dev # Use the dev Dockerfile for development
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app # Mount client directory to allow live changes
      - /app/node_modules # Ignore node_modules from being overridden
    networks:
      - app-network

  server:
    build: ./server
    ports:
      - '5000:5000'
    volumes:
      - ./server:/app # Mount the server code folder to the container
      - /app/venv # Ensure the virtual environment inside the container is not overwritten
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: pass@word
      MYSQL_DATABASE: attendit_db
    ports:
      - '3307:3306'
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
